added checkov

diff --git a/.github/workflows/docker-uc3.yml b/.github/workflows/docker-uc3.yml
--- a/.github/workflows/docker-uc3.yml
+++ b/.github/workflows/docker-uc3.yml
@@ -42,6 +42,31 @@ jobs:
         run: |
           tflint --init
           tflint --recursive
+      
+      # Install Checkov.
+      - name: Install Checkov
+        run: |
+          python -m pip install --upgrade pip
+          pip install checkov
+
+      # Run Checkov to scan Terraform files.
+      - name: Run Checkov Scan
+        run: |
+          checkov -d .  # Scan the current directory for Terraform files.
+          
+      # Optional: Upload Checkov results to GitHub.
+      - name: Upload Checkov results to GitHub
+        uses: actions/upload-artifact@v2
+        with:
+          name: checkov-results
+          path: checkov_output.txt
+
+      # Optional: Fail the workflow if Checkov finds issues.
+      - name: Fail if Checkov finds issues
+        run: |
+          if grep -q "Failed" checkov_output.txt; then
+            exit 1
+          fi
 
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v3
