add checkov

diff --git a/.github/workflows/docker-uc3.yml b/.github/workflows/docker-uc3.yml
--- a/.github/workflows/docker-uc3.yml
+++ b/.github/workflows/docker-uc3.yml
@@ -52,11 +52,20 @@ jobs:
       # Run Checkov to scan Terraform files.
       - name: Run Checkov Scan
         run: |
-          checkov -d .  # Scan the current directory for Terraform files.
+          checkov -d .  > checkov_output.txt  # Scan the current directory for Terraform files.
+      
+      - name: Check if Checkov output file exists
+        run: |
+          if [ -f checkov_output.txt ]; then
+            echo "Checkov output found!"
+          else
+            echo "Checkov output not found!"
+            exit 1
+          fi
           
       # Optional: Upload Checkov results to GitHub.
       - name: Upload Checkov results to GitHub
-        uses: actions/upload-artifact@v2
+        uses: actions/upload-artifact@v3
         with:
           name: checkov-results
           path: checkov_output.txt
